### PR TITLE
Declarative pipeline support

### LINKED ISSUE #4: Highlighting text with HTML
Hello!

Doesn't work HTML highlighting for description's text in build's parameters, but highlighting works for default Jenkins build's parameters.

Jenkins version 2.90
Persistent Parameter Plugin version 1.1

### LINKED ISSUE #8: Question: How to use this with pipelines?
How do you use this with pipeline? I can't find any docs nor snippets

```
pipeline {
    agent {
        label '...'
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)', name: 'branch', ...
        persistentStringParameter(defaultValue: 'default', description: 'gimme info', name: 'someParam')
    }
```

It results in:
`org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 7: Invalid parameter type "persistentStringParameter". Valid parameter types: [booleanParam, choice, credentials, file, gitParameter, listGitBranches, text, password, run, string] @ line 7, column 9.`

### LINKED ISSUE #9: Why is the line feed in the description field converted to < br >?How can i to resolve it?
image
image

### PR DESCRIPTION
**Pull request by ro-kr**
This adds support for declarative pipeline scripts, so that the persistent parameters can be created like the following (like requested in #8)

```Groovy
pipeline {
    parameters {
        persistentBoolean(name: 'Boolean', defaultValue: true, description: 'A boolean parameter', successfulOnly: false)
        persistentString(name: 'String', defaultValue: 'a single line', description: 'A string parameter', successfulOnly: false)
        persistentText(name: 'Text', defaultValue: 'text\nwith\nmultiple\nlines', description: 'A text parameter', successfulOnly: false)
        persistentChoice(name: 'Choices', choices: ['red', 'green', 'blue'], description: 'A choices parameter', successfulOnly: false)
    }
    ...
    stages {
        ...
    }
}
```

The parameters are also supported by the declarative snippet generator.

For this feature it's needed to bump the minimal required Jenkins version to 2.164.1. The additional code is basically copied from the build-in non-persistent variants of these parameter types.

Further visible improvements (as they exist on the non-persistent parameter types):

- Option to trim the value of the persistent string parameter.
- Proper rendering of HTML in the parameter description (see #4).

Code improvements:
- Determination of default value for build moved into method `getDefaultParameterValue()` in order to separate it from the original default value used for editing the parameter definition.
- Jelly code fixed and modernized.

resolves #8, fixes #9, fixes #4

### CODE REVIEW

**Comment by u3r** [comment]
Can someone please have a a look at it and merge?
This feature would be a fine addition to the plugin.

**Comment by arungitan** [comment]
thanks for merging this. when will it be available for automatic upgrade from Jenkins ?  our devops say Jenkins  doesn't give them the option to upgrade from 1.2 and the github release is not in .hpi format.  I created an issue #13  for the same.

**Comment by bkarakashev** [comment]
I am trying to add this in a seed job but I am getting this error:

```
Processing DSL script nonprod_deploy.jenkins
ERROR: (nonprod_deploy.jenkins, line 30) No signature of method: javaposse.jobdsl.dsl.helpers.BuildParametersContext.persistentBoolean() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:Boolean, defaultValue:true, description:A boolean parameter, ...]]
Finished: FAILURE
```

Any idea what I am doing wrong?

This is my code:

```
...
	parameters {
		persistentBoolean(name: 'Boolean', defaultValue: true, description: 'A boolean parameter', successfulOnly: false)
	}
...
```

However this works no problem:
https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.BuildParametersContext.booleanParam

**Comment by ro-kr** [comment]
Resolved #8
Fixed #9
Fixes #4

**Comment by ro-kr** [comment]
I guess this is a limitation of the Jenkins Job DSL plugin, it only supports the parameter types listed here: https://jenkinsci.github.io/job-dsl-plugin/#path/job-parameters

**Pull request merged**
